# Alacritty Configuration

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 8, y = 8 }
decorations = "none"
opacity = 0.8

[font]
normal = { family = "Fira Code" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
size = 14.0

[colors]
[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"

[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.selection]
text = "#2e3440"
background = "#88c0d0"

[cursor]
style = "Block"
unfocused_hollow = true

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
    # Standard bindings
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "F", mods = "Control|Shift", action = "SearchForward" },
    { key = "B", mods = "Control|Shift", action = "SearchBackward" },
    { key = "L", mods = "Control|Shift", action = "ClearLogNotice" },
    { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
    { key = "Home", mods = "Shift", action = "ScrollToTop" },
    { key = "End", mods = "Shift", action = "ScrollToBottom" },
]

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#bf616a"